version: "3.9"
services:
  frontend:
    container_name: vc-showcase-frontend
    build: 
      context: ./web
      dockerfile: Dockerfile
    image: showcase-web
    volumes:
      - ./web:/usr/src/app
        /app/node_modules
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    env_file:
      - ./web/.env
  backend:
    container_name: vc-showcase-backend
    build: 
      context: ./api
      dockerfile: Dockerfile
    image: showcase-api
    ports:
      - "3100:3100"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/usr/src/app
        /app/node_modules
  # dev:
  #   image: showcase-dev
  #   build:
  #     context: ./
  #     dockerfile: ./dev.dockerfile
  #   ports:
  #     - "3000:3000"
  #     - "5000:5000"
  #   volumes:
  #     - ./:/app
  