services:
  frontend:
    image: node:16.18-slim
    command: ['yarn', 'start']
    working_dir: /w/web
    ports:
      - '3000:3000'
    depends_on:
      - backend
    env_file:
      - ./web/.env
    volumes:
      - ./:/w
  verifier:
    image: node:16.18-slim
    command: ['yarn', 'start']
    working_dir: /w/verifier
    ports:
      - '3001:3001'
    depends_on:
      - backend
    env_file:
      - ./verifier/.env
    volumes:
      - ./:/w
  backend:
    image: node:16.18-slim
    command: ['yarn', 'run', 'dev']
    working_dir: /w/api
    ports:
      - '3100:3100'
    env_file:
      - ./api/.env
    volumes:
      - ./:/w
