version: "3.9"
services:
  frontend:
    image: showcase-web
    build: 
      context: ./
      dockerfile: ./web/Dockerfile
    volumes:
      - type: bind
        source: ./web/Caddyfile
        target: /etc/caddy/Caddyfile
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    env_file:
      - ./web/.env
  backend:
    image: showcase-api
    build: 
      context: ./
      dockerfile: ./api/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./api/.env
  # dev:
  #   image: showcase-dev
  #   build:
  #     context: ./
  #     dockerfile: ./dev.dockerfile
  #   ports:
  #     - "3000:3000"
  #     - "5000:5000"
  #   volumes:
  #     - ./:/app
  