name: Test & Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'yarn.lock'
      - 'web/src/**'
      - 'web/config/**'
      - 'api/src/**'
      - 'api/config/**'
env:
  REGISTRY: ghcr.io
  nodeVersion: 18.18
jobs:
  quality:
    runs-on: ubuntu-latest
    # permissions:
    #   packages: read
    #   contents: read
    steps:
    - uses: actions/checkout@v3

    - name: Setup node v${{ env.nodeVersion }}
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ env.nodeVersion }}
        registry-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      shell: bash
      run: |
        corepack enable && \
        yarn set version 3.6 && \
        yarn install --immutable

    # - name: Run tests and linting
    #   if: ${{ false }} # disable for now
    #   run: |
    #     # yarn workspaces run build
    #     # yarn workspaces run test
    #     # yarn workspaces run test:lint
    #     # yarn workspaces run test:typecheck

      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

