const palette = {
  white: '#FFFFFF',
  offWhite: '#F5F5F4',
  lightGrey: '#E5E5E5',
  grey: '#808080',
  darkGrey: '#3A3B3B',
  offBlack: '#202223',
  black: '#000000',
  blue: '#003366',
  gold: '#FCBA19',
}

/* eslint-disable no-undef */
module.exports = {
  content: ['./public/*.html', './src/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    minWidth: {
      min: '420px',
    },
    container: {
      center: true,
    },
    screens: {
      sm: '480px',
      md: '768px',
      lg: '976px',
      sxl: '1242px',
      xl: '1440px',
    },
    colors: {
      accent: palette.blue,
      background: palette.offWhite,
      text: palette.black,
      inset: palette.white,
      insetText: palette.black,
      modal: palette.white,
      modalText: palette.black,
      popup: palette.darkGrey,
      popupText: palette.white,
      primaryBtn: palette.blue,
      primaryBtnText: palette.white,
      secondaryBtn: palette.white,
      secondaryBtnText: palette.offBlack,
      icon: palette.lightGrey,
      separator: palette.lightGrey,
      progress: palette.grey,
      dark: {
        accent: palette.gold,
        background: palette.offBlack,
        text: palette.offWhite,
        inset: palette.darkGrey,
        insetText: palette.white,
        modal: palette.darkGrey,
        modalText: palette.white,
        popup: palette.darkGrey,
        popupText: palette.white,
        primaryBtn: palette.offWhite,
        primaryBtnText: palette.offBlack,
        secondaryBtn: palette.gold,
        secondaryBtnText: palette.black,
        icon: palette.offBlack,
        separator: palette.grey,
        progress: palette.grey,
      },
      white: palette.white,
      lightGrey: palette.lightGrey,
      grey: palette.grey,
      black: palette.black,
    },
    fontFamily: {
      sans: ['montserrat', 'sans-serif'],
    },
    extend: {
      transitionProperty: {
        height: 'height',
      },
    },
  },
}
